import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";
import { AlertProvider } from "@/context/AlertContext";
import { AlertPopUp } from "@/components/Alert/Alert";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Página de cadastro com mongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <AlertProvider>
        <QueryProvider>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            {children}
            <AlertPopUp />
          </body>
        </QueryProvider>
      </AlertProvider>
    </html>
  );
}
